# Generated by Django 3.2.21 on 2023-10-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
